/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import System.AddAcc;
import System.InfoNhanVien;
import javax.swing.JOptionPane;
import manager.BangLuong2;
import manager.ChucVu2;
import manager.KhenThuong2;
import manager.NhanSu2;
import manager.PhongBan2;
import manager.TrinhDo2;

/**
 *
 * @author Fvck7
 */
public class TrangChuFrame extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuFrame
     */
    public TrangChuFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Hồ sơ nhân sự");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnThongtinnhanvien = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        btnThemtaikhoan = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        btnLogout = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        btnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnPhongban = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        btnTrinhdo = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        btnChucvu = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        btnQuanlynhanvien = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        btnBangluong = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        btnKhenthuong = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang Chủ");
        setFocusCycleRoot(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/quan-ly-nhan-vien.png"))); // NOI18N

        jMenu1.setText("Hệ thống");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        btnThongtinnhanvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnThongtinnhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/user1.png"))); // NOI18N
        btnThongtinnhanvien.setText("Thông tin nhân viên");
        btnThongtinnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongtinnhanvienActionPerformed(evt);
            }
        });
        jMenu1.add(btnThongtinnhanvien);
        jMenu1.add(jSeparator2);

        btnThemtaikhoan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnThemtaikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        btnThemtaikhoan.setText("Thêm tài khoản nhân viên");
        btnThemtaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemtaikhoanActionPerformed(evt);
            }
        });
        jMenu1.add(btnThemtaikhoan);
        jMenu1.add(jSeparator10);

        btnLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(btnLogout);
        jMenu1.add(jSeparator9);

        btnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/close (1).png"))); // NOI18N
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jMenu1.add(btnExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý ");

        btnPhongban.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnPhongban.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/desk.png"))); // NOI18N
        btnPhongban.setText("Phòng ban");
        btnPhongban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhongbanActionPerformed(evt);
            }
        });
        jMenu2.add(btnPhongban);
        jMenu2.add(jSeparator3);

        btnTrinhdo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnTrinhdo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/New Folder/book.png"))); // NOI18N
        btnTrinhdo.setText("Trình độ chuyên môn");
        btnTrinhdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrinhdoActionPerformed(evt);
            }
        });
        jMenu2.add(btnTrinhdo);
        jMenu2.add(jSeparator4);

        btnChucvu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnChucvu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/position.png"))); // NOI18N
        btnChucvu.setText("Chức vụ");
        btnChucvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChucvuActionPerformed(evt);
            }
        });
        jMenu2.add(btnChucvu);
        jMenu2.add(jSeparator5);

        btnQuanlynhanvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnQuanlynhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staff.png"))); // NOI18N
        btnQuanlynhanvien.setText("Quản lý nhân viên");
        btnQuanlynhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanlynhanvienActionPerformed(evt);
            }
        });
        jMenu2.add(btnQuanlynhanvien);
        jMenu2.add(jSeparator6);

        btnBangluong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnBangluong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/salary.png"))); // NOI18N
        btnBangluong.setText("Bảng lương");
        btnBangluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBangluongActionPerformed(evt);
            }
        });
        jMenu2.add(btnBangluong);
        jMenu2.add(jSeparator8);

        btnKhenthuong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnKhenthuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bonus.png"))); // NOI18N
        btnKhenthuong.setText("Khen thưởng");
        btnKhenthuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhenthuongActionPerformed(evt);
            }
        });
        jMenu2.add(btnKhenthuong);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongtinnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongtinnhanvienActionPerformed
        // TODO add your handling code here:
        InfoNhanVien info = new InfoNhanVien();
        info.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThongtinnhanvienActionPerformed

    private void btnThemtaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemtaikhoanActionPerformed
        // TODO add your handling code here:
        AddAcc ada = new AddAcc();
        ada.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThemtaikhoanActionPerformed

    private void btnTrinhdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrinhdoActionPerformed
        // TODO add your handling code here:
        TrinhDo2 td = new TrinhDo2();
        td.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTrinhdoActionPerformed

    private void btnQuanlynhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanlynhanvienActionPerformed
        // TODO add your handling code here:
        NhanSu2 ns = new NhanSu2();
        ns.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuanlynhanvienActionPerformed

    private void btnKhenthuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhenthuongActionPerformed
        // TODO add your handling code here:
        KhenThuong2 kt = new KhenThuong2();
        kt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKhenthuongActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(btnLogout, "Bạn muốn đăng xuất");
        if (a == JOptionPane.YES_OPTION ) {
            dispose();
            LoginDialog lg = new LoginDialog(this, true);
            lg.setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBangluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBangluongActionPerformed
        // TODO add your handling code here:
        BangLuong2 bl = new BangLuong2();
        bl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBangluongActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:           
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void btnPhongbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhongbanActionPerformed
        // TODO add your handling code here:
        PhongBan2 pb = new PhongBan2();
        pb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPhongbanActionPerformed

    private void btnChucvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChucvuActionPerformed
        // TODO add your handling code here:
        ChucVu2 cv = new ChucVu2();
        cv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnChucvuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnBangluong;
    private javax.swing.JMenuItem btnChucvu;
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JMenuItem btnKhenthuong;
    private javax.swing.JMenuItem btnLogout;
    private javax.swing.JMenuItem btnPhongban;
    private javax.swing.JMenuItem btnQuanlynhanvien;
    private javax.swing.JMenuItem btnThemtaikhoan;
    private javax.swing.JMenuItem btnThongtinnhanvien;
    private javax.swing.JMenuItem btnTrinhdo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
